apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "graylog.name" . }}
    chart: {{ template "graylog.chart" . }}
    component: elasticsearch
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "graylog.name" . }}
    component: elasticsearch
    release: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: transport
    protocol: TCP
    port: 9300
    targetPort: 9300
  clusterIP: None