apiVersion: v1
kind: Service
metadata:
  name: {{ template "graylog.slave.fullname" . }}
  labels:
    name: graylog-slave
    app: {{ template "graylog.name" . }}
    chart: {{ template "graylog.chart" . }}
    component: graylog-slave
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "graylog.name" . }}
    component: graylog-slave
    release: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.graylog.web.service.internalPort }}
  clusterIP: None
